### ISSUE TITLE
Refreshing the page asks for my name again

### ISSUE THREAD

**Issue by posty72** [pixelfusion/eat-group#6]
When I refresh the page, or come back to the page again, I'm "logged out".

Recommend having some way to save the person's name and app state (localstorage?).

**Comment by posty72** [comment]
@damian-pf Did you resolve this? I think this ticket (or at least a copy) belongs on the [eat-group-vue](https://github.com/pixelfusion/eat-group-vue) repo too.

**Comment by damian-pf** [comment]
Yup, just needs deploying

**Comment by posty72** [comment]
Thanks, closing this issue. Fixed by #8
